---
output:
  word_document:
    fig_caption: yes
    # fig_height: 5
    # fig_width: 9
    reference_docx: template.docx
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

```{r echo=FALSE, warning=FALSE, message=FALSE, results="hide" }

# ##### need the following if running script from this window
# 
# # directories -------------------------------------------------------------
# 
# computer = 'pc' # set this to either 'mac' or 'pc' (Georgia = W:/ as I have string mounted differently)
# 
# if (computer=="pc") {
#   string = 'W:/'
#   sdan1 = 'Y:/'
# } else if (computer=="mac") {
#   string = '/Volumes/string-mbd/'
#   sdan1 = '/Volumes/sdan1/'
# }
# 
# database_location = paste0(string, "Database/Master Psychometric Database/") # tasks database also located here
# IRTA_tracker_location = paste0(string, "Database/Master Participant Tracker/")
# scripts = paste0(string, "Database/Database_Scripts_Github/") # temp useful directory while scripts are still under development
# inpatient_location = paste0(database_location, "Inpatient/") 
# inpatient_backup = paste0(inpatient_location, "Backup/") 
# inpatient_summary_location = paste0(inpatient_location, "Reports/")
# 
# # packages ----------------------------------------------------------------
# 
# suppressPackageStartupMessages(library(readxl))
# suppressPackageStartupMessages(library(writexl))
# suppressPackageStartupMessages(library(tidyr))
# suppressPackageStartupMessages(library(dplyr))
# suppressPackageStartupMessages(library(rmarkdown))
# suppressPackageStartupMessages(library(eeptools))
# suppressPackageStartupMessages(library(openxlsx))
# suppressPackageStartupMessages(library(data.table))
# suppressPackageStartupMessages(library(reshape2))
# suppressPackageStartupMessages(library(stringr))
# suppressPackageStartupMessages(library(lubridate))
# suppressPackageStartupMessages(library(ggplot2))
# suppressPackageStartupMessages(library(rlang))
# suppressPackageStartupMessages(library(purrr))
# suppressPackageStartupMessages(library(tidyverse))
# suppressPackageStartupMessages(library(shiny))
# suppressPackageStartupMessages(library(knitr))
# suppressPackageStartupMessages(library(flextable))
# 
# # functions ---------------------------------------------------------------
# 
# count_na <- function(x) sum(is.na(x))
# 
# FitFlextableToPage <- function(ft, pgwidth = 10){
#   ft_out <- ft %>% autofit(., add_h = 0.3)
#   ft_out <- width(ft_out, width = dim(ft_out)$widths*10.5/(flextable_dim(ft_out)$widths))
#   return(ft_out)
# }
# 
# # other to load if running script here ------------------------------------
# 
# to_change <- read_excel(paste0(scripts, "to_change_before_running_master_script.xlsx"))
# todays_date_formatted <- c(to_change$todays_date_formatted)
# todays_date_formatted <- as.Date(todays_date_formatted)
# # todays_date_formatted <- as.Date("2019-12-16")

```

```{r echo=FALSE, warning=FALSE, message=FALSE, results="hide" }

# Loading data ------------------------------------------------------------

inpatient_database_file <- list.files(path = paste0(inpatient_location), pattern = "^MASTER_DATABASE_Inpatient", all.files = FALSE,
                                 full.names = FALSE, recursive = FALSE, ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)
inpatient_database_file_time <- file.mtime(paste0(inpatient_location, inpatient_database_file)) %>% as.Date()
inpatient_database_combined <- tibble(File=c(inpatient_database_file), Date=c(inpatient_database_file_time)) %>% arrange(desc(Date)) %>% slice(1)

if (exists("MATCH_tracker")==FALSE) {
        MATCH_tracker <- read_excel(paste0(inpatient_location, inpatient_database_combined[1])) %>% mutate_all(as.character)
        MATCH_tracker$Clinical_Visit_Date <- as.Date(MATCH_tracker$Clinical_Visit_Date)
}

cbt_database_file <- list.files(path = paste0(CBT_location), pattern = "^MASTER_DATABASE_CBT", all.files = FALSE,
                                 full.names = FALSE, recursive = FALSE, ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)
cbt_database_file_time <- file.mtime(paste0(CBT_location, cbt_database_file)) %>% as.Date()
cbt_database_combined <- tibble(File=c(cbt_database_file), Date=c(cbt_database_file_time)) %>% arrange(desc(Date)) %>% slice(1)
        
if (exists("CBT_report")==FALSE) {
        CBT_report <- read_excel(paste0(CBT_location, cbt_database_combined[1])) %>% mutate_all(as.character)
        CBT_report$Clinical_Visit_Date <- as.Date(CBT_report$Clinical_Visit_Date)
}

# changing date formats
todays_date <- todays_date_formatted %>% format(., "%B %d %Y")
MATCH_tracker$Clinical_Visit_Date2 <- format(MATCH_tracker$Clinical_Visit_Date, "%b-%d")
MATCH_tracker$Clinical_Visit_Date3 <- format(MATCH_tracker$Clinical_Visit_Date, "%B-%d-%Y")
CBT_report$Clinical_Visit_Date2 <- format(CBT_report$Clinical_Visit_Date, "%b-%d")
CBT_report$Clinical_Visit_Date3 <- format(CBT_report$Clinical_Visit_Date, "%B-%d-%Y")

inpatient_database_updated <- inpatient_database_combined$Date[1] %>% format(., "%B %d %Y")
outpatient_database_updated <- cbt_database_combined$Date[1] %>% format(., "%B %d %Y")

# Data needed for patient summaries -------------------------------------

current_inpatients <- MATCH_tracker %>% group_by(Initials) %>% arrange(Clinical_Visit_Date) %>% slice(n()) %>% ungroup() %>% 
  filter(Eligible=="Include" | is.na(Eligible)) %>% select(FIRST_NAME, LAST_NAME, Initials, SDAN, Age_at_visit, SEX, c_ksadsdx_dx_detailed, IRTA_tracker)
inpatient_list <- c(current_inpatients$Initials)

current_outpatients <- CBT_report %>% group_by(Initials) %>% arrange(Clinical_Visit_Date) %>% slice(n()) %>% ungroup() %>% 
  filter(Eligible=="Include" | is.na(Eligible)) %>% 
  # filter(!str_detect(Clinical_Visit_Type, "o0")) %>% 
  select(FIRST_NAME, LAST_NAME, Initials, SDAN, Age_at_visit, SEX, c_ksadsdx_dx_detailed, IRTA_tracker)
outpatient_list <- c(current_outpatients$Initials)

# clinical database - inpatient 
psychometric_data_i <- MATCH_tracker %>% filter(Initials %in% inpatient_list) %>% 
  select(Initials, Clinical_Visit_Date, Clinical_Visit_Date2, Clinical_Visit_Date3, Clinical_Visit_Type, Clinical_Visit_Number, 
    s_mfq1w_tot, p_mfq1w_tot, s_ari1w_tot, p_ari1w_tot, s_scared_tot, p_scared_tot, s_shaps_tot, s_lsas_tot, s_lsasad_tot, 
    c_cybocs_ob_tot, c_cybocs_com_tot, s_chocir_symptom_tot, s_chocir_impairment_tot
    # , c_ygtss_severity_tot, c_ygtss_tot
    )
psychometric_data_i[,7:ncol(psychometric_data_i)] <- sapply(psychometric_data_i[,7:ncol(psychometric_data_i)], as.numeric)
psychometric_data_i[,7:ncol(psychometric_data_i)] <- sapply(psychometric_data_i[,7:ncol(psychometric_data_i)], round, 0)
psychometric_data_i$s_lsasad_tot <- coalesce(psychometric_data_i$s_lsasad_tot, psychometric_data_i$s_lsas_tot)

# clinical database - outpatient 
psychometric_data_o <- CBT_report %>% filter(Initials %in% outpatient_list) %>% 
  select(Initials, Clinical_Visit_Date, Clinical_Visit_Date2, Clinical_Visit_Date3, Clinical_Visit_Type, Clinical_Visit_Number, 
    s_mfq1w_tot, p_mfq1w_tot, s_ari1w_tot, p_ari1w_tot, s_scared_tot, p_scared_tot, s_shaps_tot, s_lsas_tot, s_lsasad_tot)
psychometric_data_o[,7:ncol(psychometric_data_o)] <- sapply(psychometric_data_o[,7:ncol(psychometric_data_o)], as.numeric)
psychometric_data_o[,7:ncol(psychometric_data_o)] <- sapply(psychometric_data_o[,7:ncol(psychometric_data_o)], round, 0)
psychometric_data_o$s_lsasad_tot <- coalesce(psychometric_data_o$s_lsasad_tot, psychometric_data_o$s_lsas_tot)

# variation of autofit formula for table optimization ---------------------

FitFlextableToPage3 <- function(ft, pgwidth = 8){
  ft_out <- ft %>% autofit(., add_h = 0.15)
  ft_out <- width(ft_out, width = dim(ft_out)$widths*8.5/(flextable_dim(ft_out)$widths))
  return(ft_out)
}

```

# Clinician supervision: overview of participants in treatment. Report generated on `r todays_date`.

***

##### Inpatients: last updated `r inpatient_database_updated`

***

```{r echo=FALSE, warning=FALSE, message=FALSE, results="asis", fig.width=10, fig.height=6}

if (nrow(current_inpatients)==0) {
  
  print("No current inpatients")
  cat("  \n",  "  \n***")
  
  } else {
    
    for(i in seq(nrow(current_inpatients))) {
    # iter=1
    iter <- as.numeric(i)
    
    Participant <- inpatient_list[iter]
    temp_demo <- current_inpatients %>% filter(Initials==Participant)
    temp_psych <- psychometric_data_i %>% filter(Initials==Participant) %>% arrange(Clinical_Visit_Date)
  
    cat("  \n",  "  \n###",  iter, "->", as.character(temp_demo[1,3]), "-> SDAN:", as.character(temp_demo[1,4]), 
        "-> Age:", as.character(temp_demo[1,5]), "-> Sex:", as.character(temp_demo[1,6]), "-> Diagnosis:", as.character(temp_demo[1,7]), 
        "-> IRTA:", as.character(temp_demo[1,8]))
  
    cat("  \nQuestionnaire totals:")
    questionnaire_data <- flextable(temp_psych, col_keys = c("Clinical_Visit_Number", "Clinical_Visit_Date3", "s_mfq1w_tot", "p_mfq1w_tot", 
      "s_ari1w_tot", "p_ari1w_tot", "s_scared_tot", "p_scared_tot", "s_shaps_tot", "s_lsasad_tot", "c_cybocs_ob_tot", "c_cybocs_com_tot", 
      "s_chocir_symptom_tot", "s_chocir_impairment_tot"
      # ,  "c_ygtss_severity_tot", "c_ygtss_tot"
      )) %>% 
      set_header_labels(., Clinical_Visit_Number="Week",  Clinical_Visit_Date3="Date", s_mfq1w_tot="MFQ:S", p_mfq1w_tot="MFQ:P", s_ari1w_tot="ARI:S",
        p_ari1w_tot="ARI:P", s_scared_tot="SCARED:S", p_scared_tot="SCARED:P", s_shaps_tot="SHAPS", s_lsasad_tot="LSAS:A", c_cybocs_ob_tot="CYBOCS:O", 
        c_cybocs_com_tot="CYBOCS:C", s_chocir_symptom_tot="CHOCIR:S", s_chocir_impairment_tot="CHOCIR:I"
        # , c_ygtss_severity_tot="YGTSS:S", c_ygtss_tot="YGTSS:T"
        ) %>% 
      colformat_num(j = c("Clinical_Visit_Number", "Clinical_Visit_Date3", "s_mfq1w_tot", "p_mfq1w_tot", "s_ari1w_tot", "p_ari1w_tot", 
        "s_scared_tot", "p_scared_tot", "s_shaps_tot", "s_lsasad_tot", "c_cybocs_ob_tot", "c_cybocs_com_tot", 
        "s_chocir_symptom_tot", "s_chocir_impairment_tot"
        # , "c_ygtss_severity_tot", "c_ygtss_tot"
        ), digits = 0, na_str = "") %>% 
      fontsize(., size=10, part="all") %>% align(., align = "left", part="all") %>%
      FitFlextableToPage(.)
    cat(knit_print(questionnaire_data))
    
    cat("  \n",  "  \n***")
  
    }
}
  
```


##### Outpatients: last updated `r outpatient_database_updated`

***

```{r echo=FALSE, warning=FALSE, message=FALSE, results="asis", fig.width=10, fig.height=6}

if (nrow(current_outpatients)==0) {
  
  print("No current outpatients")
  cat("  \n",  "  \n***")
  
  } else {
    
    for(i in seq(nrow(current_outpatients))) {
    # iter=1
    iter <- as.numeric(i)
    
    Participant <- outpatient_list[iter]
    temp_demo <- current_outpatients %>% filter(Initials==Participant)
    temp_psych <- psychometric_data_o %>% filter(Initials==Participant) %>% arrange(Clinical_Visit_Date)
  
    cat("  \n",  "  \n###",  iter, "->", as.character(temp_demo[1,3]), "-> SDAN:", as.character(temp_demo[1,4]), 
        "-> Age:", as.character(temp_demo[1,5]), "-> Sex:", as.character(temp_demo[1,6]), "-> Diagnosis:", as.character(temp_demo[1,7]), 
        "-> IRTA:", as.character(temp_demo[1,8]))
  
    cat("  \nQuestionnaire totals:")
    questionnaire_data <- flextable(temp_psych, col_keys = c("Clinical_Visit_Number", "Clinical_Visit_Date3", "s_mfq1w_tot", "p_mfq1w_tot", 
      "s_ari1w_tot", "p_ari1w_tot", "s_scared_tot", "p_scared_tot", "s_shaps_tot", "s_lsasad_tot")) %>% 
      set_header_labels(., Clinical_Visit_Number="Week",  Clinical_Visit_Date3="Date", s_mfq1w_tot="MFQ:S", p_mfq1w_tot="MFQ:P", s_ari1w_tot="ARI:S",
        p_ari1w_tot="ARI:P", s_scared_tot="SCARED:S", p_scared_tot="SCARED:P", s_shaps_tot="SHAPS", s_lsasad_tot="LSAS:A") %>% 
      colformat_num(j = c("Clinical_Visit_Number", "Clinical_Visit_Date3", "s_mfq1w_tot", "p_mfq1w_tot", "s_ari1w_tot", "p_ari1w_tot", 
        "s_scared_tot", "p_scared_tot", "s_shaps_tot", "s_lsasad_tot"), digits = 0, na_str = "") %>% 
      fontsize(., size=10, part="all") %>% align(., align = "left", part="all") %>%
      FitFlextableToPage3(.)
    cat(knit_print(questionnaire_data))
    
    cat("  \n",  "  \n***")
  
      }
    
  }
  
```

```{r echo=FALSE, warning=FALSE, message=FALSE, results="hide" }

# removing finished variables

rm(temp_demo, temp_psych, questionnaire_data, FitFlextableToPage3)
rm(Participant, i, iter, current_inpatients, current_outpatients, psychometric_data_i, psychometric_data_o, inpatient_list, outpatient_list)
rm(inpatient_database_file, inpatient_database_file_time, inpatient_database_combined)
rm(cbt_database_file, cbt_database_file_time, cbt_database_combined)

```
