---
title: "MOOD BRAIN & DEVELOPMENT UNIT"
output:
  word_document:
    fig_caption: yes
    fig_height: 5
    fig_width: 7
    reference_docx: template.docx
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# !diagnostics off
```

```{r echo=FALSE, warning=FALSE, message=FALSE, results="hide" }

# ##### need the following if running script from this window
# 
# # directories -------------------------------------------------------------
# 
# computer = 'pc' # set this to either 'mac' or 'pc' (Georgia = W:/ as I have string mounted differently)
# 
# if (computer=="pc") {
#   string = 'W:/'
#   sdan1 = 'Y:/'
# } else if (computer=="mac") {
#   string = '/Volumes/string-mbd/'
#   sdan1 = '/Volumes/sdan1/'
# }
# 
# database_location = paste0(string, "Database/Master Psychometric Database/") # tasks database also located here
# IRTA_tracker_location = paste0(string, "Database/Master Participant Tracker/")
# scripts = paste0(string, "Database/Database_Scripts_Github/") # temp useful directory while scripts are still under development
# clinician_sheet_location = paste0(string, "Minutes and conversation archives/Thursday Clinical Meetings/Clinician Sheet/")
# sdq_pull = paste0(database_location, "SDQ_pull/")
# CBT_location = paste0(string, "Database/Master Psychometric Database/CBT/")
# 
# # packages ----------------------------------------------------------------
# 
# suppressPackageStartupMessages(library(readxl))
# suppressPackageStartupMessages(library(writexl))
# suppressPackageStartupMessages(library(tidyr))
# suppressPackageStartupMessages(library(dplyr))
# suppressPackageStartupMessages(library(rmarkdown))
# suppressPackageStartupMessages(library(eeptools))
# suppressPackageStartupMessages(library(openxlsx))
# suppressPackageStartupMessages(library(data.table))
# suppressPackageStartupMessages(library(reshape2))
# suppressPackageStartupMessages(library(stringr))
# suppressPackageStartupMessages(library(lubridate))
# suppressPackageStartupMessages(library(ggplot2))
# suppressPackageStartupMessages(library(rlang))
# suppressPackageStartupMessages(library(purrr))
# suppressPackageStartupMessages(library(tidyverse))
# suppressPackageStartupMessages(library(shiny))
# suppressPackageStartupMessages(library(knitr))
# suppressPackageStartupMessages(library(flextable))
# 
# # functions ---------------------------------------------------------------
# 
# count_na <- function(x) sum(is.na(x))
# 
# FitFlextableToPage <- function(ft, pgwidth = 10){
#   ft_out <- ft %>% autofit(., add_h = 0.3)
#   ft_out <- width(ft_out, width = dim(ft_out)$widths*10.5/(flextable_dim(ft_out)$widths))
#   return(ft_out)
# }
# 
# # other to load if running script here ------------------------------------
# 
# to_change <- read_excel(paste0(scripts, "to_change_before_running_master_script.xlsx"))
# max_tasks <- c(to_change$max_tasks)
# latest_sdq_pull <- c(to_change$latest_sdq_pull)
# # todays_date_formatted <- c(to_change$todays_date_formatted)
# # todays_date_formatted <- as.Date(todays_date_formatted)
# todays_date_formatted <- as.Date("2019-12-13")

```

```{r echo=FALSE, warning=FALSE, message=FALSE, results="hide" }

# Loading data ------------------------------------------------------------

todays_date <- todays_date_formatted %>% format(., "%B %d %Y")

if (exists("master_IRTA_latest")==FALSE) {
        irta_master_file <- list.files(path = paste0(IRTA_tracker_location), pattern = "^MASTER_IRTA_DATABASE", all.files = FALSE,
                                 full.names = FALSE, recursive = FALSE,
                                 ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)
        irta_master_file_time <- file.mtime(paste0(IRTA_tracker_location, "/", irta_master_file)) %>% as.Date()
        irta_master_combined <- tibble(File=c(irta_master_file), Date=c(irta_master_file_time)) %>% arrange(desc(Date)) %>% slice(1)
        master_IRTA_latest <- read_excel(paste0(IRTA_tracker_location, irta_master_combined[1]))
        date_variabes <- c("DOB", "Screening_Start_Date", "Referral_Date", "Consent_Date", "Clinical_Visit_Date", "Clinicals_date", "Overall_date")
        for(i in seq_len(max_tasks)) { date_variabes <- c(date_variabes, paste0("Task", i, "_Date"))}
        master_IRTA_latest[date_variabes] <- lapply(master_IRTA_latest[date_variabes], as.Date)
        rm(i, date_variabes, irta_master_file, irta_master_file_time, irta_master_combined)
} 

if (exists("master_IRTA_screens_latest")==FALSE) {
        irta_ongoing_screens_file <- list.files(path = paste0(IRTA_tracker_location), pattern = "^REFERRAL_AND_SCREENING_DATABASE", all.files = FALSE,
                                 full.names = FALSE, recursive = FALSE,
                                 ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)
        irta_ongoing_screens_file_time <- file.mtime(paste0(IRTA_tracker_location, "/", irta_ongoing_screens_file)) %>% as.Date()
        irta_ongoing_screens_combined <- tibble(File=c(irta_ongoing_screens_file), Date=c(irta_ongoing_screens_file_time)) %>% 
          arrange(desc(Date)) %>% slice(1)
        master_IRTA_screens_latest <- read_excel(paste0(IRTA_tracker_location, irta_ongoing_screens_combined[1]))
        date_variabes <- c("DOB", "Screening_Start_Date", "Referral_Date", "Consent_Date", "Clinical_Visit_Date", "Clinicals_date", "Overall_date")
        master_IRTA_screens_latest[date_variabes] <- lapply(master_IRTA_screens_latest[date_variabes], as.Date) 
        rm(date_variabes, irta_ongoing_screens_file, irta_ongoing_screens_file_time, irta_ongoing_screens_combined)
}

# Relevant info from trackers ------------------------------------------------------------

# from current screens 

common_identifiers_screening <- master_IRTA_screens_latest %>% 
  select(FIRST_NAME, LAST_NAME, Initials, Participant_Type, IRTA_tracker, PLUSID, DAWBA_ID, DOB, Age_at_visit, SEX, 
         Eligible, Scheduling_status, Clinical_Visit_Date, Clinical_Visit_Type, NIMH_Clinician, Referral_Date, Screening_Start_Date, 
         Parent_e_consented, Child_e_assented, Parent_DAWBA_completed, Child_DAWBA_completed, City, State, Primary_clinician, Marital_Status, Metal, 
         Screening_notes, Referral_other_notes, Eligibility_notes, Scheduling_status_notes, Treatment_Notes, Referral_Source) %>% 
  mutate(source="screens")

# from active patient list 

common_identifiers_sheduling <- master_IRTA_latest %>% 
  select(FIRST_NAME, LAST_NAME, Initials, Participant_Type, IRTA_tracker, PLUSID, DAWBA_ID, DOB, Age_at_visit, SEX, 
         Eligible, Scheduling_status, Clinical_Visit_Date, Clinical_Visit_Type, NIMH_Clinician, Referral_Date, Screening_Start_Date, 
         Parent_e_consented, Child_e_assented, Parent_DAWBA_completed, Child_DAWBA_completed, City, State, Primary_clinician, Marital_Status, Metal, 
         Screening_notes, Referral_other_notes, Eligibility_notes, Scheduling_status_notes, Treatment_Notes, Referral_Source) %>% 
    group_by(Initials) %>% arrange(Clinical_Visit_Date) %>% slice(1) %>% ungroup() %>% mutate(source="irta trackers")

# merging these 
  
common_identifiers <- merge.default(common_identifiers_sheduling, common_identifiers_screening, all=TRUE) %>% filter(IRTA_tracker!="REMOVED")

# tidying up 

name_variables <- c("FIRST_NAME", "LAST_NAME", "Initials", "Participant_Type")
common_identifiers[name_variables] <- lapply(common_identifiers[name_variables], toupper)
numeric_variables <- c("Eligible", "Scheduling_status", "Parent_e_consented", "Child_e_assented", "Parent_DAWBA_completed", "Child_DAWBA_completed")
common_identifiers[numeric_variables] <- lapply(common_identifiers[numeric_variables], as.numeric)
common_identifiers[numeric_variables] <- lapply(common_identifiers[numeric_variables], replace_na, 666)

common_identifiers$Overall_date <- coalesce(as.Date(common_identifiers$Referral_Date, "%Y-%m-%d"), as.Date(common_identifiers$Screening_Start_Date, "%Y-%m-%d")) %>%
  coalesce(., as.Date(common_identifiers$Clinical_Visit_Date, "%Y-%m-%d"))
common_identifiers <- common_identifiers %>% filter(!is.na(Overall_date)) %>% filter(Clinical_Visit_Date>=todays_date_formatted | is.na(Clinical_Visit_Date))

```

```{r echo=FALSE, warning=FALSE, message=FALSE, results="hide" }

# Extracting screening information from SDQ+ --------------------------

# loading raw SDQ+ data 

SDQ_Data_Download_raw <- read.delim(paste0(sdq_pull, latest_sdq_pull, ".txt"),  quote="", 
                                    encoding="UTF-8", row.names = NULL, header = TRUE, stringsAsFactors = FALSE)

# creating date column 

sdq_dates <- c("modedate", "dateadded", "Done", "mindate", "maxdate")
SDQ_Data_Download_raw$dateadded <- gsub("0019", "2019", SDQ_Data_Download_raw$dateadded, fixed=TRUE)
SDQ_Data_Download_raw$dateadded <- gsub("0018", "2018", SDQ_Data_Download_raw$dateadded, fixed=TRUE)
SDQ_Data_Download_raw[sdq_dates] <- lapply(SDQ_Data_Download_raw[sdq_dates], as.Date, "%Y-%m-%d")

SDQ_Data_Download_raw$Overall_date <- coalesce(as.Date(SDQ_Data_Download_raw$modedate, "%Y-%m-%d"), as.Date(SDQ_Data_Download_raw$dateadded, "%Y-%m-%d")) %>%
  coalesce(., as.Date(SDQ_Data_Download_raw$maxdate, "%Y-%m-%d")) %>% coalesce(., as.Date(SDQ_Data_Download_raw$mindate, "%Y-%m-%d")) %>% 
  coalesce(., as.Date(SDQ_Data_Download_raw$Done, "%Y-%m-%d")) 
  
# changing column names & doing some clean up

sdq_columns <- read_excel(paste0(database_location, "other_data_never_delete/sdq_column_names_and_descriptions.xlsx"))
setnames(SDQ_Data_Download_raw, old=c(sdq_columns$old_name), new=c(sdq_columns$new_name), skip_absent=TRUE)

```

```{r echo=FALSE, warning=FALSE, message=FALSE, results="hide" }

# pulling out the parent demographic screener questionnaire 

p_demo_screen_sdq <- SDQ_Data_Download_raw %>% select(PLUSID, Overall_date, matches("p_demo_screen_")) %>% 
  rename(p_demo_screen_date = "Overall_date") %>% filter(!is.na(p_demo_screen_date)) %>% distinct(., .keep_all = TRUE)

# removing NAs

p_demo_screen_sdq[,3:ncol(p_demo_screen_sdq)] <- lapply(p_demo_screen_sdq[,3:ncol(p_demo_screen_sdq)], na_if, "-2")
p_demo_screen_sdq[,3:ncol(p_demo_screen_sdq)] <- lapply(p_demo_screen_sdq[,3:ncol(p_demo_screen_sdq)], na_if, "")
p_demo_screen_sdq$no_columns <- p_demo_screen_sdq %>% select(matches('p_demo_screen_')) %>% select(-p_demo_screen_date) %>% ncol() %>% as.numeric()
p_demo_screen_sdq$NA_count <- p_demo_screen_sdq %>% select(matches('p_demo_screen_')) %>% select(-p_demo_screen_date) %>% apply(., 1, count_na)
p_demo_screen_sdq$diff <- c(p_demo_screen_sdq$no_columns - p_demo_screen_sdq$NA_count)
p_demo_screen_sdq <- p_demo_screen_sdq %>% filter(diff>0) %>% select(-no_columns, -NA_count, -diff)

# matching to relevant participants 

p_demo_screen_sdq_plus_tracker <- left_join(common_identifiers, p_demo_screen_sdq, by = "PLUSID")

##### data merge cleanup

p_demo_screen_sdq_plus_tracker$p_demo_screen_sex_child <- recode(p_demo_screen_sdq_plus_tracker$p_demo_screen_sex_child, "0"="FEMALE", "1"="MALE", .missing = NULL)
p_demo_screen_sdq_plus_tracker$SEX <- coalesce(p_demo_screen_sdq_plus_tracker$SEX, p_demo_screen_sdq_plus_tracker$p_demo_screen_sex_child)
p_demo_screen_sdq_plus_tracker$Age_at_visit <- coalesce(p_demo_screen_sdq_plus_tracker$Age_at_visit, as.numeric(p_demo_screen_sdq_plus_tracker$p_demo_screen_age_child))
p_demo_screen_sdq_plus_tracker$State <- coalesce(p_demo_screen_sdq_plus_tracker$State, p_demo_screen_sdq_plus_tracker$p_demo_screen_demographics_state)
p_demo_screen_sdq_plus_tracker$Referral_Source <- coalesce(p_demo_screen_sdq_plus_tracker$Referral_Source, p_demo_screen_sdq_plus_tracker$p_demo_screen_how_knew_study)

# dx of note
p_demo_screen_sdq_plus_tracker$p_demo_screen_ever_asd <- recode(p_demo_screen_sdq_plus_tracker$p_demo_screen_ever_asd, "1"="ASD", "0"="No", .missing = NULL)
p_demo_screen_sdq_plus_tracker$p_demo_screen_medic_dx_kidn <- recode(p_demo_screen_sdq_plus_tracker$p_demo_screen_medic_dx_kidn, "1"="Kidney condition", "0"="No", .missing = NULL)
p_demo_screen_sdq_plus_tracker$p_demo_screen_medic_dx_thyr <- recode(p_demo_screen_sdq_plus_tracker$p_demo_screen_medic_dx_thyr, "1"="Thyroid condition", "0"="No", .missing = NULL)
p_demo_screen_sdq_plus_tracker$p_demo_screen_medic_dx_card <- recode(p_demo_screen_sdq_plus_tracker$p_demo_screen_medic_dx_card, "1"="Cardiac condition", "0"="No", .missing = NULL)
p_demo_screen_sdq_plus_tracker$p_demo_screen_medic_dx_seiz <- recode(p_demo_screen_sdq_plus_tracker$p_demo_screen_medic_dx_seiz, "1"="Seizure disorder", "0"="No", .missing = NULL)
p_demo_screen_sdq_plus_tracker$p_demo_screen_medic_dx_birth_brain <- 
  recode(p_demo_screen_sdq_plus_tracker$p_demo_screen_medic_dx_birth_brain, "1"="Brain defect at birth", "0"="No", .missing = NULL)
p_demo_screen_sdq_plus_tracker$p_demo_screen_ever_head_injury <- recode(p_demo_screen_sdq_plus_tracker$p_demo_screen_ever_head_injury, "1"="Head injury", "0"="No", .missing = NULL)
p_demo_screen_sdq_plus_tracker$p_demo_screen_color_blind <- recode(p_demo_screen_sdq_plus_tracker$p_demo_screen_color_blind, "1"="Colour blind", "0"="No", .missing = NULL)
p_demo_screen_sdq_plus_tracker$p_demo_screen_sensitivity <- 
  recode(p_demo_screen_sdq_plus_tracker$p_demo_screen_sensitivity, "1"="Increased sensitivity to sensory stimuli", "0"="No", .missing = NULL)

p_demo_screen_sdq_plus_tracker$Diagnoses_of_note <- paste(p_demo_screen_sdq_plus_tracker$p_demo_screen_ever_asd, p_demo_screen_sdq_plus_tracker$p_demo_screen_medic_dx_kidn, 
                                                          p_demo_screen_sdq_plus_tracker$p_demo_screen_medic_dx_thyr, p_demo_screen_sdq_plus_tracker$p_demo_screen_medic_dx_card, 
                                                          p_demo_screen_sdq_plus_tracker$p_demo_screen_medic_dx_seiz, p_demo_screen_sdq_plus_tracker$p_demo_screen_medic_dx_birth_brain,
                                                          p_demo_screen_sdq_plus_tracker$p_demo_screen_ever_head_injury, p_demo_screen_sdq_plus_tracker$p_demo_screen_color_blind, 
                                                          p_demo_screen_sdq_plus_tracker$p_demo_screen_color_blind, p_demo_screen_sdq_plus_tracker$p_demo_screen_sensitivity, 
                                                          "Psych dx", p_demo_screen_sdq_plus_tracker$p_demo_screen_psych_dx, sep="; ")

p_demo_screen_sdq_plus_tracker$Diagnoses_of_note <- gsub("Psych dx; NA", "", p_demo_screen_sdq_plus_tracker$Diagnoses_of_note, fixed=TRUE)
p_demo_screen_sdq_plus_tracker$Diagnoses_of_note <- gsub("NA; ", "", p_demo_screen_sdq_plus_tracker$Diagnoses_of_note, fixed=TRUE)
p_demo_screen_sdq_plus_tracker$Diagnoses_of_note <- gsub("No; ", "", p_demo_screen_sdq_plus_tracker$Diagnoses_of_note, fixed=TRUE)
p_demo_screen_sdq_plus_tracker$Diagnoses_of_note <- na_if(p_demo_screen_sdq_plus_tracker$Diagnoses_of_note, "")

p_demo_screen_sdq_plus_tracker$p_demo_screen_child_under_care_of <- gsub("[", "", p_demo_screen_sdq_plus_tracker$p_demo_screen_child_under_care_of, fixed=TRUE)
p_demo_screen_sdq_plus_tracker$p_demo_screen_child_under_care_of <- gsub("]", "", p_demo_screen_sdq_plus_tracker$p_demo_screen_child_under_care_of, fixed=TRUE)
p_demo_screen_sdq_plus_tracker$p_demo_screen_child_under_care_of <- gsub("'care_psych'", "Psychiatrist", p_demo_screen_sdq_plus_tracker$p_demo_screen_child_under_care_of, fixed=TRUE)
p_demo_screen_sdq_plus_tracker$p_demo_screen_child_under_care_of <- gsub("'care_therap'", "Therapsit", p_demo_screen_sdq_plus_tracker$p_demo_screen_child_under_care_of, fixed=TRUE)
p_demo_screen_sdq_plus_tracker$p_demo_screen_child_under_care_of <- gsub("'care_pediatr'", "Pediatrician", p_demo_screen_sdq_plus_tracker$p_demo_screen_child_under_care_of, fixed=TRUE)

# metal screen
p_demo_screen_sdq_plus_tracker$p_demo_screen_metal_surgery <- 
  recode(p_demo_screen_sdq_plus_tracker$p_demo_screen_metal_surgery, "1"="Metal staples/wire structures/implants", "0"="No", .missing = NULL)
p_demo_screen_sdq_plus_tracker$p_demo_screen_metal_dental <- 
  recode(p_demo_screen_sdq_plus_tracker$p_demo_screen_metal_dental, "1"="Dental implants/braces/permanent retainer", "0"="No", .missing = NULL)
p_demo_screen_sdq_plus_tracker$p_demo_screen_pierc_tattoo <- 
  recode(p_demo_screen_sdq_plus_tracker$p_demo_screen_pierc_tattoo, "1"="Tattoo/piercing that cannot be removed", "0"="No", .missing = NULL)
p_demo_screen_sdq_plus_tracker$p_demo_screen_iud_synt_hair <- 
  recode(p_demo_screen_sdq_plus_tracker$p_demo_screen_iud_synt_hair, "1"="IUD/non-removable synthetic hair", "0"="No", .missing = NULL)
p_demo_screen_sdq_plus_tracker$p_demo_screen_metal_work <- 
  recode(p_demo_screen_sdq_plus_tracker$p_demo_screen_metal_work, "1"="Ever done any welding or metal work", "0"="No", .missing = NULL)
p_demo_screen_sdq_plus_tracker$p_demo_screen_plan_metal <- 
  recode(p_demo_screen_sdq_plus_tracker$p_demo_screen_plan_metal, "1"="Plans in the next six months to get braces, any implanted metal, etc.", "0"="No", .missing = NULL)

p_demo_screen_sdq_plus_tracker$Metal_screen <- paste("Notes from IRTA tracker", p_demo_screen_sdq_plus_tracker$Metal, "Parent report on SDQ", 
                                                     p_demo_screen_sdq_plus_tracker$p_demo_screen_metal_surgery, p_demo_screen_sdq_plus_tracker$p_demo_screen_metal_dental, 
                                                     p_demo_screen_sdq_plus_tracker$p_demo_screen_pierc_tattoo, p_demo_screen_sdq_plus_tracker$p_demo_screen_iud_synt_hair, 
                                                     p_demo_screen_sdq_plus_tracker$p_demo_screen_metal_work, p_demo_screen_sdq_plus_tracker$p_demo_screen_plan_metal, sep="; ")

p_demo_screen_sdq_plus_tracker$Metal_screen <- gsub("NA; ", "", p_demo_screen_sdq_plus_tracker$Metal_screen, fixed=TRUE)
p_demo_screen_sdq_plus_tracker$Metal_screen <- gsub("No; ", "", p_demo_screen_sdq_plus_tracker$Metal_screen, fixed=TRUE)
p_demo_screen_sdq_plus_tracker$Metal_screen <- gsub("Notes from IRTA tracker; Parent report on SDQ; ", "", p_demo_screen_sdq_plus_tracker$Metal_screen, fixed=TRUE)
p_demo_screen_sdq_plus_tracker$Metal_screen <- gsub("; No", "", p_demo_screen_sdq_plus_tracker$Metal_screen, fixed=TRUE)
p_demo_screen_sdq_plus_tracker$Metal_screen <- na_if(p_demo_screen_sdq_plus_tracker$Metal_screen, "NA")

# diagnostics 
p_demo_screen_sdq_plus_tracker$p_demo_screen_ever_ekg <- recode(p_demo_screen_sdq_plus_tracker$p_demo_screen_ever_ekg, "1"="EKG", "0"="No", .missing = NULL)
p_demo_screen_sdq_plus_tracker$p_demo_screen_ever_eeg <- recode(p_demo_screen_sdq_plus_tracker$p_demo_screen_ever_eeg, "1"="EEG", "0"="No", .missing = NULL)
p_demo_screen_sdq_plus_tracker$p_demo_screen_ever_ct <- recode(p_demo_screen_sdq_plus_tracker$p_demo_screen_ever_ct, "1"="CT", "0"="No", .missing = NULL)
p_demo_screen_sdq_plus_tracker$p_demo_screen_ever_mri <- recode(p_demo_screen_sdq_plus_tracker$p_demo_screen_ever_mri, "1"="MRI", "0"="No", .missing = NULL)

p_demo_screen_sdq_plus_tracker$Diagnostic_imaging <- 
  paste("Test", p_demo_screen_sdq_plus_tracker$p_demo_screen_ever_ekg, "Reason", p_demo_screen_sdq_plus_tracker$p_demo_screen_reason_ekg, 
        "Result", p_demo_screen_sdq_plus_tracker$p_demo_screen_results_ekg, "Test", p_demo_screen_sdq_plus_tracker$p_demo_screen_ever_eeg,
        "Reason", p_demo_screen_sdq_plus_tracker$p_demo_screen_reason_eeg, "Result", p_demo_screen_sdq_plus_tracker$p_demo_screen_results_eeg,
        "Test", p_demo_screen_sdq_plus_tracker$p_demo_screen_ever_ct, "Reason", p_demo_screen_sdq_plus_tracker$p_demo_screen_reason_ct,
        "Result", p_demo_screen_sdq_plus_tracker$p_demo_screen_results_ct, "Test", p_demo_screen_sdq_plus_tracker$p_demo_screen_ever_mri,
        "Reason", p_demo_screen_sdq_plus_tracker$p_demo_screen_reason_mri, "Result", p_demo_screen_sdq_plus_tracker$p_demo_screen_results_mri, sep="; ")

p_demo_screen_sdq_plus_tracker$Diagnostic_imaging <- gsub("Test; NA; Reason; NA; Result; NA", "", p_demo_screen_sdq_plus_tracker$Diagnostic_imaging, fixed=TRUE)
p_demo_screen_sdq_plus_tracker$Diagnostic_imaging <- gsub("Test; No; Reason; NA; Result; NA", "", p_demo_screen_sdq_plus_tracker$Diagnostic_imaging, fixed=TRUE)
p_demo_screen_sdq_plus_tracker$Diagnostic_imaging <- gsub("; ; ; ", "", p_demo_screen_sdq_plus_tracker$Diagnostic_imaging, fixed=TRUE)
p_demo_screen_sdq_plus_tracker$Diagnostic_imaging <- gsub("; ; ", "", p_demo_screen_sdq_plus_tracker$Diagnostic_imaging, fixed=TRUE)
p_demo_screen_sdq_plus_tracker$Diagnostic_imaging <- na_if(p_demo_screen_sdq_plus_tracker$Diagnostic_imaging, "")

# medications 
p_demo_screen_sdq_plus_tracker$Medications <- paste("Medication name", p_demo_screen_sdq_plus_tracker$p_demo_screen_med1, "Dose", p_demo_screen_sdq_plus_tracker$p_demo_screen_dose1,
                                                    "Medication name", p_demo_screen_sdq_plus_tracker$p_demo_screen_med2, "Dose", p_demo_screen_sdq_plus_tracker$p_demo_screen_dose2, 
                                                    "Medication name", p_demo_screen_sdq_plus_tracker$p_demo_screen_med3, "Dose", p_demo_screen_sdq_plus_tracker$p_demo_screen_dose3,
                                                    "Medication name", p_demo_screen_sdq_plus_tracker$p_demo_screen_med4, "Dose", p_demo_screen_sdq_plus_tracker$p_demo_screen_dose4,
                                                    sep="; ")
p_demo_screen_sdq_plus_tracker$Medications <- gsub("Medication name; NA; Dose; NA; ", "", p_demo_screen_sdq_plus_tracker$Medications, fixed=TRUE)
p_demo_screen_sdq_plus_tracker$Medications <- gsub("Medication name; NA; Dose; NA", "", p_demo_screen_sdq_plus_tracker$Medications, fixed=TRUE)
p_demo_screen_sdq_plus_tracker$Medications <- gsub("Dose; NA; ", "", p_demo_screen_sdq_plus_tracker$Medications, fixed=TRUE)

```

```{r echo=FALSE, warning=FALSE, message=FALSE, results="hide" }

# pulling out the screening parent mfq  

p_mfq_screen_sdq <- SDQ_Data_Download_raw %>% select(PLUSID, Overall_date, matches("p_mfq_")) %>% select(-p_mfq_parent_other) %>% 
  rename(p_mfq_screen_date = "Overall_date") %>% filter(!is.na(p_mfq_screen_date)) %>% distinct(., .keep_all = TRUE)

# removing NAs

p_mfq_screen_sdq[,3:ncol(p_mfq_screen_sdq)] <- lapply(p_mfq_screen_sdq[,3:ncol(p_mfq_screen_sdq)], na_if, "-2")
p_mfq_screen_sdq[,3:ncol(p_mfq_screen_sdq)] <- lapply(p_mfq_screen_sdq[,3:ncol(p_mfq_screen_sdq)], na_if, "")
p_mfq_screen_sdq$no_columns <- p_mfq_screen_sdq %>% select(matches('p_mfq_')) %>% select(-p_mfq_screen_date) %>% ncol() %>% as.numeric()
p_mfq_screen_sdq$NA_count <- p_mfq_screen_sdq %>% select(matches('p_mfq_')) %>% select(-p_mfq_screen_date) %>% apply(., 1, count_na)
p_mfq_screen_sdq$diff <- c(p_mfq_screen_sdq$no_columns - p_mfq_screen_sdq$NA_count)
p_mfq_screen_sdq <- p_mfq_screen_sdq %>% filter(diff>0) %>% select(-no_columns, -NA_count, -diff)
p_mfq_screen_sdq <- p_mfq_screen_sdq %>% group_by(PLUSID) %>% arrange(p_mfq_screen_date) %>% slice(1) %>% ungroup()
  
# tidying variables 

p_mfq_screen_sdq$MFQ_tot <- p_mfq_screen_sdq %>% select(matches("p_mfq_")) %>% select(-p_mfq_screen_date, -p_mfq_parent) %>% rowSums(na.rm=TRUE)
p_mfq_screen_sdq$p_mfq_parent <- recode(p_mfq_screen_sdq$p_mfq_parent, "1"="Mother", "2"="Father", "0"="Other", .missing = NULL)

```

```{r echo=FALSE, warning=FALSE, message=FALSE, results="hide" }

# merging both together 

sdq_plus_tracker <- left_join(p_demo_screen_sdq_plus_tracker, p_mfq_screen_sdq, by = "PLUSID") 

sdq_plus_tracker$Notes <- paste("Referral notes", sdq_plus_tracker$Referral_other_notes, "Screening notes", sdq_plus_tracker$Screening_notes, 
                                "Eligibility notes", sdq_plus_tracker$Eligibility_notes, "Scheduling notes", sdq_plus_tracker$Scheduling_status_notes, 
                                "Treatment notes", sdq_plus_tracker$Treatment_Notes, "Parent notes", sdq_plus_tracker$p_demo_screen_demogrphic_notes, sep="; ")

sdq_plus_tracker$Notes <- gsub("Referral notes; NA; ", "", sdq_plus_tracker$Notes, fixed=TRUE)
sdq_plus_tracker$Notes <- gsub("Screening notes; NA; ", "", sdq_plus_tracker$Notes, fixed=TRUE)
sdq_plus_tracker$Notes <- gsub("Eligibility notes; NA; ", "", sdq_plus_tracker$Notes, fixed=TRUE)
sdq_plus_tracker$Notes <- gsub("Scheduling notes; NA; ", "", sdq_plus_tracker$Notes, fixed=TRUE)
sdq_plus_tracker$Notes <- gsub("Treatment notes; NA; ", "", sdq_plus_tracker$Notes, fixed=TRUE)
sdq_plus_tracker$Notes <- gsub("Parent notes; NA", "", sdq_plus_tracker$Notes, fixed=TRUE)
sdq_plus_tracker$Notes <- na_if(sdq_plus_tracker$Notes, "")

sdq_plus_tracker <- sdq_plus_tracker %>% 
  select(FIRST_NAME, LAST_NAME, Initials, Participant_Type, IRTA_tracker, PLUSID, DAWBA_ID, DOB, Age_at_visit, SEX, City, State, Marital_Status,
         Eligible, Scheduling_status, Clinical_Visit_Date, Clinical_Visit_Type, NIMH_Clinician, Referral_Date, Screening_Start_Date, Referral_Source, 
         Parent_e_consented, Child_e_assented, Parent_DAWBA_completed, Child_DAWBA_completed, p_mfq_screen_date, MFQ_tot, p_mfq_parent, 
         p_demo_screen_date, Diagnoses_of_note, p_demo_screen_child_under_care_of, Primary_clinician, Medications, Metal_screen, Diagnostic_imaging, Notes, source)

# splitting into subgroups

numeric_variables2 <- c("Parent_e_consented", "Child_e_assented", "Parent_DAWBA_completed", "Child_DAWBA_completed")

# 1. scheduled 
scheduled_v1 <- sdq_plus_tracker %>% filter(!is.na(Clinical_Visit_Date)) %>% filter(Eligible<4 | Eligible==666)
scheduled_v1[numeric_variables] <- lapply(scheduled_v1[numeric_variables], na_if, 666)
scheduled_v1$Eligible <- recode(scheduled_v1$Eligible, "0"="Fully eligible", "1"="Eligible but can't scan", 
                                "2"="On hold: contact again after specified amount of time", "3"="On hold: low priority", .missing = NULL)
scheduled_v1$Scheduling_status <- recode(scheduled_v1$Scheduling_status, "0"="Screening", "1"="Scheduling", "2"="Scheduled", 
                                         "3"="Completed (visit has passed)", "4"="Scheduling on hold pending clinician follow up", .missing = NULL)
scheduled_v1$Marital_Status <- recode(scheduled_v1$Marital_Status, "0"="Married", "1"="Divorced; joint custody", "2"="Divorced; sole custody", "3"="Never married", .missing = NULL)
scheduled_v1[numeric_variables2] <- lapply(scheduled_v1[numeric_variables2], FUN = function(x) recode(x, "0"="No", "1"="Yes", .missing = "Unknown"))

# 2. scheduling (completed screening)
scheduling_v1 <- sdq_plus_tracker %>% filter(source=="irta trackers") %>% filter(is.na(Clinical_Visit_Date)) %>% filter(Eligible<4 | Eligible==666)
scheduling_v1[numeric_variables] <- lapply(scheduling_v1[numeric_variables], na_if, 666)
scheduling_v1$Eligible <- recode(scheduling_v1$Eligible, "0"="Fully eligible", "1"="Eligible but can't scan", 
                                "2"="On hold: contact again after specified amount of time", "3"="On hold: low priority", .missing = NULL)
scheduling_v1$Scheduling_status <- recode(scheduling_v1$Scheduling_status, "0"="Screening", "1"="Scheduling", "2"="Scheduled", 
                                         "3"="Completed (visit has passed)", "4"="Scheduling on hold pending clinician follow up", .missing = NULL)
scheduling_v1$Marital_Status <- recode(scheduling_v1$Marital_Status, "0"="Married", "1"="Divorced; joint custody", "2"="Divorced; sole custody", "3"="Never married", .missing = NULL)
scheduling_v1[numeric_variables2] <- lapply(scheduling_v1[numeric_variables2], FUN = function(x) recode(x, "0"="No", "1"="Yes", .missing = "Unknown"))

# 3. finished screening, ready to review 
ready_to_review <- sdq_plus_tracker %>% filter(source=="screens") %>% filter(Eligible<4 | Eligible==666) %>% 
  filter(Parent_DAWBA_completed==1 & Child_DAWBA_completed==1)
ready_to_review[numeric_variables] <- lapply(ready_to_review[numeric_variables], na_if, 666)
ready_to_review$Eligible <- recode(ready_to_review$Eligible, "0"="Fully eligible", "1"="Eligible but can't scan", 
                                "2"="On hold: contact again after specified amount of time", "3"="On hold: low priority", .missing = NULL)
ready_to_review$Scheduling_status <- 
  recode(ready_to_review$Scheduling_status, "0"="Screening", "1"="Scheduling", "2"="Scheduled", 
                                         "3"="Completed (visit has passed)", "4"="Scheduling on hold pending clinician follow up", .missing = NULL)
ready_to_review$Marital_Status <- 
  recode(ready_to_review$Marital_Status, "0"="Married", "1"="Divorced; joint custody", "2"="Divorced; sole custody", "3"="Never married", .missing = NULL)
ready_to_review[numeric_variables2] <- lapply(ready_to_review[numeric_variables2], FUN = function(x) recode(x, "0"="No", "1"="Yes", .missing = "Unknown"))
ready_to_review$Referral_Date <- coalesce(ready_to_review$Referral_Date, ready_to_review$Screening_Start_Date)

# 4. still undergoing screening 
screening <- sdq_plus_tracker %>% filter(source=="screens") %>% filter(Eligible<4 | Eligible==666) %>% 
  filter(Parent_e_consented!=1 | Child_e_assented!=1 | Parent_DAWBA_completed!=1 | Child_DAWBA_completed!=1)
screening[numeric_variables] <- lapply(screening[numeric_variables], na_if, 666)
screening$Eligible <- recode(screening$Eligible, "0"="Fully eligible", "1"="Eligible but can't scan", 
                                "2"="On hold: contact again after specified amount of time", "3"="On hold: low priority", .missing = NULL)
screening$Scheduling_status <- recode(screening$Scheduling_status, "0"="Screening", "1"="Scheduling", "2"="Scheduled", 
                                         "3"="Completed (visit has passed)", "4"="Scheduling on hold pending clinician follow up", .missing = NULL)
screening$Marital_Status <- recode(screening$Marital_Status, "0"="Married", "1"="Divorced; joint custody", "2"="Divorced; sole custody", "3"="Never married", .missing = NULL)
screening[numeric_variables2] <- lapply(screening[numeric_variables2], FUN = function(x) recode(x, "0"="No", "1"="Yes", .missing = "Unknown"))
screening$Referral_Date <- coalesce(screening$Referral_Date, screening$Screening_Start_Date)
screening <- screening %>% filter(!is.na(FIRST_NAME) & !is.na(LAST_NAME)) %>% filter(FIRST_NAME!="UNKNOWN" & LAST_NAME!="UNKNOWN")

```

##### Clinical meeting sheet, `r todays_date` 

***

##### 1. Scheduled for eval: `r nrow(scheduled_v1)`
 
```{r echo=FALSE, warning=FALSE, message=FALSE, results="asis"}

for(i in seq(nrow(scheduled_v1))) {
  # iter=3
  iter <- as.numeric(i)

  temp <- scheduled_v1 %>% slice(eval(iter))
  
  cat("  \n",  "  \n###",  iter, "-", temp[1,1], "", temp[1,2], "(", temp[1,3], ")")
  
  demo_table <- flextable(temp, col_keys = c("Participant_Type", "IRTA_tracker", "DOB", "Age_at_visit", "SEX", "City", "State", "Marital_Status", 
                                       "Eligible", "DAWBA_ID", "Referral_Source", "MFQ_tot", "Clinical_Visit_Date", "NIMH_Clinician")) %>%
    set_header_labels(., Participant_Type="Type", IRTA_tracker="IRTA", DOB="DOB", Age_at_visit="Age", SEX="Sex", City="City", State="State", Marital_Status="Marital Status",
                    Eligible="Eligible", DAWBA_ID="DAWBA_ID", Referral_Source="Referral Source", MFQ_tot="MFQ tot", Clinical_Visit_Date="Clinical Visit Date", 
                    NIMH_Clinician="Clinician") %>%
    fontsize(., size=8, part="all") %>% align(., align = "left", part="all") %>% FitFlextableToPage(.)

  cat(knit_print(demo_table))
  
  notes_table <- flextable(temp, col_keys = c("Diagnoses_of_note", "Medications", "Metal_screen", "Notes")) %>%
    set_header_labels(., Diagnoses_of_note="Diagnoses of note", Medications="Medications", Metal_screen="Metal screen", Notes="Notes") %>%
    fontsize(., size=8, part="all") %>% align(., align = "left", part="all") %>% FitFlextableToPage(.)
  
  cat(knit_print(notes_table))
  
}
  
```

***

\pagebreak

##### 2. Scheduling for eval: `r nrow(scheduling_v1)`
 
```{r echo=FALSE, warning=FALSE, message=FALSE, results="asis"}

for(i in seq(nrow(scheduling_v1))) {
  # iter=3
  iter <- as.numeric(i)

  temp <- scheduling_v1 %>% slice(eval(iter))
  
  cat("  \n",  "  \n###",  iter, "-", temp[1,1], "", temp[1,2], "(", temp[1,3], ")")
  
  demo_table <- flextable(temp, col_keys = c("Participant_Type", "IRTA_tracker", "DOB", "Age_at_visit", "SEX", "City", "State", "Marital_Status", 
                                       "Eligible", "DAWBA_ID", "Referral_Source", "MFQ_tot", "Referral_Date")) %>%
    set_header_labels(., Participant_Type="Type", IRTA_tracker="IRTA", DOB="DOB", Age_at_visit="Age", SEX="Sex", City="City", State="State", Marital_Status="Marital Status",
                    Eligible="Eligible", DAWBA_ID="DAWBA_ID", Referral_Source="Referral Source", MFQ_tot="MFQ tot", Referral_Date="Screening Since") %>%
    fontsize(., size=8, part="all") %>% align(., align = "left", part="all") %>% FitFlextableToPage(.)

  cat(knit_print(demo_table))
  
  notes_table <- flextable(temp, col_keys = c("Diagnoses_of_note", "Medications", "Metal_screen", "Notes")) %>%
    set_header_labels(., Diagnoses_of_note="Diagnoses of note", Medications="Medications", Metal_screen="Metal screen", Notes="Notes") %>%
    fontsize(., size=8, part="all") %>% align(., align = "left", part="all") %>% FitFlextableToPage(.)
  
  cat(knit_print(notes_table))
  
}
  
```

***

\pagebreak

##### 3. Ready to review: `r nrow(ready_to_review)`
 
```{r echo=FALSE, warning=FALSE, message=FALSE, results="asis"}

  for(i in seq(nrow(ready_to_review))) {
  # iter=3
    iter <- as.numeric(i)
  
    temp <- ready_to_review %>% slice(eval(iter))
  
    cat("  \n",  "  \n###",  iter, "-", temp[1,1], "", temp[1,2], "(", temp[1,3], ")")
  
    demo_table <- flextable(temp, col_keys = c("Participant_Type", "IRTA_tracker", "DOB", "Age_at_visit", "SEX", "City", "State", "Marital_Status",
                                         "Eligible", "DAWBA_ID", "Referral_Source", "MFQ_tot", "Referral_Date")) %>%
      set_header_labels(., Participant_Type="Type", IRTA_tracker="IRTA", DOB="DOB", Age_at_visit="Age", SEX="Sex", City="City", State="State", Marital_Status="Marital Status",
                      Eligible="Eligible", DAWBA_ID="DAWBA_ID", Referral_Source="Referral Source", MFQ_tot="MFQ tot", Referral_Date="Screening Since") %>%
      fontsize(., size=8, part="all") %>% align(., align = "left", part="all") %>% FitFlextableToPage(.)
  
    cat(knit_print(demo_table))
    
    referral_table <- flextable(temp, col_keys = c("Parent_DAWBA_completed", "Child_DAWBA_completed", 
                                                   "p_demo_screen_child_under_care_of", "Primary_clinician", "Diagnostic_imaging")) %>%
      set_header_labels(., Parent_DAWBA_completed="Parent DAWBA", Child_DAWBA_completed="Child DAWBA", p_demo_screen_child_under_care_of="Clinician Type", 
                        Primary_clinician="Clinician Name", Diagnostic_imaging="Diagnostic_imaging") %>%
      fontsize(., size=8, part="all") %>% align(., align = "left", part="all") %>% FitFlextableToPage(.)
  
    cat(knit_print(referral_table))
  
    notes_table <- flextable(temp, col_keys = c("Diagnoses_of_note", "Medications", "Metal_screen", "Notes")) %>%
      set_header_labels(., Diagnoses_of_note="Diagnoses of note", Medications="Medications", Metal_screen="Metal screen", Notes="Notes") %>%
      fontsize(., size=8, part="all") %>% align(., align = "left", part="all") %>% FitFlextableToPage(.)
  
    cat(knit_print(notes_table))
  
  }
  
```

***

\pagebreak

##### 3. Screening: `r nrow(screening)`

```{r echo=FALSE, warning=FALSE, message=FALSE, results="asis"}
  
  for(i in seq(nrow(screening))) {
    # iter=3
    iter <- as.numeric(i)
  
    temp <- screening %>% slice(eval(iter))
  
    cat("  \n",  "  \n###",  iter, "-", temp[1,1], "", temp[1,2], "(", temp[1,3], ")")
  
    demo_table <- flextable(temp, col_keys = c("Participant_Type", "IRTA_tracker", "DOB", "Age_at_visit", "SEX", "City", "State", "Marital_Status",
                                         "Eligible", "DAWBA_ID", "Referral_Source", "MFQ_tot", "Referral_Date")) %>%
      set_header_labels(., Participant_Type="Type", IRTA_tracker="IRTA", DOB="DOB", Age_at_visit="Age", SEX="Sex", City="City", State="State", Marital_Status="Marital Status",
                      Eligible="Eligible", DAWBA_ID="DAWBA_ID", Referral_Source="Referral Source", MFQ_tot="MFQ tot", Referral_Date="Screening Since") %>%
      fontsize(., size=8, part="all") %>% align(., align = "left", part="all") %>% FitFlextableToPage(.)
  
    cat(knit_print(demo_table))
    
    referral_table <- flextable(temp, col_keys = c("Parent_e_consented", "Child_e_assented", "Parent_DAWBA_completed", "Child_DAWBA_completed", 
                                                   "p_demo_screen_child_under_care_of", "Primary_clinician", "Diagnostic_imaging")) %>%
      set_header_labels(., Parent_e_consented="Parent Consented", Child_e_assented="Child Assented", Parent_DAWBA_completed="Parent DAWBA", 
                        Child_DAWBA_completed="Child DAWBA", p_demo_screen_child_under_care_of="Clinician Type", Primary_clinician="Clinician Name", 
                        Diagnostic_imaging="Diagnostic_imaging") %>%
      fontsize(., size=8, part="all") %>% align(., align = "left", part="all") %>% FitFlextableToPage(.)
  
    cat(knit_print(referral_table))
  
    notes_table <- flextable(temp, col_keys = c("Diagnoses_of_note", "Medications", "Metal_screen", "Notes")) %>%
      set_header_labels(., Diagnoses_of_note="Diagnoses of note", Medications="Medications", Metal_screen="Metal screen", Notes="Notes") %>%
      fontsize(., size=8, part="all") %>% align(., align = "left", part="all") %>% FitFlextableToPage(.)
  
    cat(knit_print(notes_table))
  
  }
  
```

```{r echo=FALSE, warning=FALSE, message=FALSE, results="hide" }

# removing finished variables

rm(sdq_dates, common_identifiers_screening, common_identifiers_sheduling, fill_names, SDQ_Data_Download_raw, sdq_columns, p_demo_screen_sdq,
   name_variables, numeric_variables, screening, scheduled_v1, scheduling_v1, p_demo_screen_sdq_plus_tracker, ready_to_review, common_identifiers, 
   temp, iter, i, ready_to_review2, screening2, demo_table, referral_table, notes_table, p_mfq_screen_sdq, sdq_plus_tracker, numeric_variables2)

```
