---
output:
  word_document:
    fig_caption: yes
    # fig_height: 5
    # fig_width: 9
    reference_docx: template.docx
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

```{r echo=FALSE, warning=FALSE, message=FALSE, results="hide" }

# ##### need the following if running script from this window
# 
# # directories -------------------------------------------------------------
# 
# computer = 'pc' # set this to either 'mac' or 'pc' (Georgia = W:/ as I have string mounted differently)
# 
# if (computer=="pc") {
#   string = 'W:/'
#   sdan1 = 'Y:/'
# } else if (computer=="mac") {
#   string = '/Volumes/string-mbd/'
#   sdan1 = '/Volumes/sdan1/'
# }
# 
# database_location = paste0(string, "Database/Master Psychometric Database/") # tasks database also located here
# IRTA_tracker_location = paste0(string, "Database/Master Participant Tracker/")
# scripts = paste0(string, "Database/Database_Scripts_Github/") # temp useful directory while scripts are still under development
# inpatient_location = paste0(database_location, "Inpatient/") 
# inpatient_backup = paste0(inpatient_location, "Backup/") 
# inpatient_summary_location = paste0(inpatient_location, "Reports/")
# 
# # packages ----------------------------------------------------------------
# 
# suppressPackageStartupMessages(library(readxl))
# suppressPackageStartupMessages(library(writexl))
# suppressPackageStartupMessages(library(tidyr))
# suppressPackageStartupMessages(library(dplyr))
# suppressPackageStartupMessages(library(rmarkdown))
# suppressPackageStartupMessages(library(eeptools))
# suppressPackageStartupMessages(library(openxlsx))
# suppressPackageStartupMessages(library(data.table))
# suppressPackageStartupMessages(library(reshape2))
# suppressPackageStartupMessages(library(stringr))
# suppressPackageStartupMessages(library(lubridate))
# suppressPackageStartupMessages(library(ggplot2))
# suppressPackageStartupMessages(library(rlang))
# suppressPackageStartupMessages(library(purrr))
# suppressPackageStartupMessages(library(tidyverse))
# suppressPackageStartupMessages(library(shiny))
# suppressPackageStartupMessages(library(knitr))
# suppressPackageStartupMessages(library(flextable))
# 
# # functions ---------------------------------------------------------------
# 
# count_na <- function(x) sum(is.na(x))
# 
# FitFlextableToPage <- function(ft, pgwidth = 10){
#   ft_out <- ft %>% autofit(., add_h = 0.3)
#   ft_out <- width(ft_out, width = dim(ft_out)$widths*10.5/(flextable_dim(ft_out)$widths))
#   return(ft_out)
# }
# 
# # other to load if running script here ------------------------------------
# 
# to_change <- read_excel(paste0(scripts, "to_change_before_running_master_script.xlsx"))
# todays_date_formatted <- c(to_change$todays_date_formatted)
# todays_date_formatted <- as.Date(todays_date_formatted)
# # todays_date_formatted <- as.Date("2019-12-16")

```

```{r echo=FALSE, warning=FALSE, message=FALSE, results="hide" }

# Loading data ------------------------------------------------------------

if (exists("MATCH_tracker")==FALSE) {
        inpatient_database_file <- list.files(path = paste0(inpatient_location), pattern = "^MASTER_DATABASE_Inpatient", all.files = FALSE,
                                 full.names = FALSE, recursive = FALSE, ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)
        inpatient_database_file_time <- file.mtime(paste0(inpatient_location, inpatient_database_file)) %>% as.Date()
        inpatient_database_combined <- tibble(File=c(inpatient_database_file), Date=c(inpatient_database_file_time)) %>% arrange(desc(Date)) %>% slice(1)
        MATCH_tracker <- read_excel(paste0(inpatient_location, inpatient_database_combined[1])) %>% mutate_all(as.character)
        MATCH_tracker$Clinical_Visit_Date <- as.Date(MATCH_tracker$Clinical_Visit_Date)
        rm(inpatient_database_file, inpatient_database_file_time, inpatient_database_combined)
}

if (exists("s_mfq1d_final")==FALSE) {
        inpatient_database_file <- list.files(path = paste0(inpatient_location), pattern = "^MASTER_DATABASE_daily_MFQ", all.files = FALSE,
                                 full.names = FALSE, recursive = FALSE, ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)
        inpatient_database_file_time <- file.mtime(paste0(inpatient_location, inpatient_database_file)) %>% as.Date()
        inpatient_database_combined <- tibble(File=c(inpatient_database_file), Date=c(inpatient_database_file_time)) %>% arrange(desc(Date)) %>% slice(1)
        s_mfq1d_final <- read_excel(paste0(inpatient_location, inpatient_database_combined[1])) %>% mutate_all(as.character)
        s_mfq1d_final$s_mfq1d_date <- as.Date(s_mfq1d_final$s_mfq1d_date)
        rm(inpatient_database_file, inpatient_database_file_time, inpatient_database_combined)
        }

# changing date formats
todays_date <- todays_date_formatted %>% format(., "%B %d %Y")
MATCH_tracker$Clinical_Visit_Date2 <- format(MATCH_tracker$Clinical_Visit_Date, "%b-%d")
MATCH_tracker$Clinical_Visit_Date3 <- format(MATCH_tracker$Clinical_Visit_Date, "%B-%d-%Y")
s_mfq1d_final$s_mfq1d_date2 <- format(s_mfq1d_final$s_mfq1d_date, "%b-%d")
s_mfq1d_final$s_mfq1d_date3 <- format(s_mfq1d_final$s_mfq1d_date, "%B-%d-%Y")

# Data needed for inpatient summaries -------------------------------------

current_inpatients <- MATCH_tracker %>% group_by(Initials) %>% arrange(Clinical_Visit_Date) %>% slice(n()) %>% ungroup() %>% 
  filter(Eligible=="Include" | is.na(Eligible)) %>% select(FIRST_NAME, LAST_NAME, Initials, SDAN, Age_at_visit, SEX, c_ksadsdx_dx_detailed, IRTA_tracker)

inpatient_list <- c(current_inpatients$Initials)

# clinical database
psychometric_data <- MATCH_tracker %>% filter(Initials %in% inpatient_list) %>% 
  select(Initials, Clinical_Visit_Date, Clinical_Visit_Date2, Clinical_Visit_Date3, Clinical_Visit_Type, Clinical_Visit_Number, s_mfq1w_tot, s_ari1w_tot,
         s_scared_tot, s_shaps_tot, s_lsas_tot, s_vadis_tot, s_rumination_tot, s_chocir_symptom_tot, s_chocir_impairment_tot, s_seq_tot, p_conners_tot,
         c_snap_tot, c_cybocs_ob_tot, c_cybocs_com_tot, c_ygtss_severity_tot, c_ygtss_tot)
psychometric_data[,7:ncol(psychometric_data)] <- sapply(psychometric_data[,7:ncol(psychometric_data)], as.numeric)
psychometric_data[,7:ncol(psychometric_data)] <- sapply(psychometric_data[,7:ncol(psychometric_data)], round, 0)

# daily MFQs
daily_mfqs <- s_mfq1d_final %>% filter(Initials %in% inpatient_list) %>% 
  select(Initials, s_mfq1d_date, s_mfq1d_date3, s_mfq1d_tot) %>% mutate(s_mfq1d_tot = as.numeric(s_mfq1d_tot)) %>% arrange(s_mfq1d_date)

# medications 
medication_data <- MATCH_tracker %>% filter(Initials %in% inpatient_list) %>% 
  select(Initials, Clinical_Visit_Date, Clinical_Visit_Date2, Clinical_Visit_Date3, Clinical_Visit_Type, Clinical_Visit_Number, matches("c_medsclin_"))

medication_data$Medications <- paste("Medication 1: ", medication_data$c_medsclin_med1name, ", ", medication_data$c_medsclin_med1dose, medication_data$c_medsclin_med1unit, 
                          ", ", medication_data$c_medsclin_med1freq, ", ", medication_data$c_medsclin_med1notes,  "; ", 
                          "Medication 2: ", medication_data$c_medsclin_med2name, ", ", medication_data$c_medsclin_med2dose, medication_data$c_medsclin_med2unit, 
                          ", ", medication_data$c_medsclin_med2freq, ", ", medication_data$c_medsclin_med2notes, "; ", 
                          "Medication 3: ", medication_data$c_medsclin_med3name, ", ", medication_data$c_medsclin_med3dose, medication_data$c_medsclin_med3unit, 
                          ", ", medication_data$c_medsclin_med3freq, ", ", medication_data$c_medsclin_med3notes, "; ", 
                          "Medication 4: ", medication_data$c_medsclin_med4name, ", ", medication_data$c_medsclin_med4dose, medication_data$c_medsclin_med4unit, 
                          ", ", medication_data$c_medsclin_med4freq, ", ", medication_data$c_medsclin_med4notes, "; ", 
                          "Medication 5: ", medication_data$c_medsclin_med5name, ", ", medication_data$c_medsclin_med5dose, medication_data$c_medsclin_med5unit, 
                          ", ", medication_data$c_medsclin_med5freq, ", ", medication_data$c_medsclin_med5notes, "; ", 
                          "Medication 6: ", medication_data$c_medsclin_med6name, ", ", medication_data$c_medsclin_med6dose, medication_data$c_medsclin_med6unit, 
                          ", ", medication_data$c_medsclin_med6freq, ", ", medication_data$c_medsclin_med6notes, "; ", 
                          "Medication 7: ", medication_data$c_medsclin_med7name, ", ", medication_data$c_medsclin_med7dose, medication_data$c_medsclin_med7unit, 
                          ", ", medication_data$c_medsclin_med7freq, ", ", medication_data$c_medsclin_med7notes, "; ", 
                          "Medication 8: ", medication_data$c_medsclin_med8name, ", ", medication_data$c_medsclin_med8dose, medication_data$c_medsclin_med8unit, 
                          ", ", medication_data$c_medsclin_med8freq, ", ", medication_data$c_medsclin_med8notes, sep="")

medication_data$Medications <- gsub("Medication 1: NA, NANA, NA, NA; ", "", medication_data$Medications, fixed=TRUE)
medication_data$Medications <- gsub("Medication 2: NA, NANA, NA, NA; ", "", medication_data$Medications, fixed=TRUE)
medication_data$Medications <- gsub("Medication 3: NA, NANA, NA, NA; ", "", medication_data$Medications, fixed=TRUE)
medication_data$Medications <- gsub("Medication 4: NA, NANA, NA, NA; ", "", medication_data$Medications, fixed=TRUE)
medication_data$Medications <- gsub("Medication 5: NA, NANA, NA, NA; ", "", medication_data$Medications, fixed=TRUE)
medication_data$Medications <- gsub("Medication 6: NA, NANA, NA, NA; ", "", medication_data$Medications, fixed=TRUE)
medication_data$Medications <- gsub("Medication 7: NA, NANA, NA, NA; ", "", medication_data$Medications, fixed=TRUE)
medication_data$Medications <- gsub("Medication 8: NA, NANA, NA, NA", "", medication_data$Medications, fixed=TRUE)
medication_data$Medications <- gsub(", NA, NA", "", medication_data$Medications, fixed=TRUE)
medication_data$Medications <- gsub("Medication 1: none, 0na, na, NA; ", "", medication_data$Medications, fixed=TRUE)
medication_data$Medications <- gsub(", NA;", ";", medication_data$Medications, fixed=TRUE)
medication_data$Medications <- na_if(medication_data$Medications, "")

medication_data <- medication_data %>% select(Initials, Clinical_Visit_Date, Clinical_Visit_Date2, Clinical_Visit_Date3, Clinical_Visit_Type, 
                                              Clinical_Visit_Number, c_medsclin_treatment_changes, Medications, c_medsclin_othernotes)

for(i in seq(nrow(current_inpatients))) {
  # iter=1
  iter <- as.numeric(i)
  Participant <- inpatient_list[iter]
  med_temp <- medication_data %>% filter(Initials==Participant)
  med_repeats <- med_temp %>% filter(c_medsclin_treatment_changes==0)
  
  if (nrow(med_repeats)!=0) {
      for(j in seq(nrow(med_repeats))) {
        # iter2=1
        iter2 <- as.numeric(j)
        med_temp <- med_temp %>% mutate(temp=ifelse(c_medsclin_treatment_changes == 0, lag(Medications, order_by = Clinical_Visit_Date), Medications))
        med_temp$Medications <- coalesce(med_temp$Medications, med_temp$temp)
      }
  med_temp <- med_temp %>% filter(c_medsclin_treatment_changes==0) %>% select(-temp)
  medication_data <- medication_data %>% filter(is.na(c_medsclin_treatment_changes) | c_medsclin_treatment_changes==1)
  medication_data <- merge.default(medication_data, med_temp, all=TRUE)
  }
}

medication_data$Medication_list <- paste(medication_data$Medications, "other notes overall: ", medication_data$c_medsclin_othernotes, sep="")
medication_data$Medication_list <- na_if(medication_data$Medication_list, "NAother notes overall: NA")
medication_data$Medication_list <- gsub("; other notes overall: NA", "", medication_data$Medication_list, fixed=TRUE)

medication_data <- medication_data %>% select(-Medications, -c_medsclin_othernotes, -c_medsclin_treatment_changes) %>% group_by(Initials) %>% 
  arrange(Clinical_Visit_Date) %>% slice(1, n()) %>% ungroup()

# variation of autofit formula for table optimization ---------------------

FitFlextableToPage2 <- function(ft, pgwidth = 10){
  ft_out <- ft %>% autofit(., add_h = 0.15)
  ft_out <- width(ft_out, width = dim(ft_out)$widths*10.5/(flextable_dim(ft_out)$widths))
  return(ft_out)
}

```

##### Inpatient summary, `r todays_date` 

***

```{r echo=FALSE, warning=FALSE, message=FALSE, results="asis", fig.width=10, fig.height=6}

for(i in seq(nrow(current_inpatients))) {
  # iter=1
  iter <- as.numeric(i)
  
  Participant <- inpatient_list[iter]
  temp_demo <- current_inpatients %>% filter(Initials==Participant)
  temp_meds <- medication_data %>% filter(Initials==Participant) %>% arrange(as.numeric(Clinical_Visit_Number))
  temp_psych <- psychometric_data %>% filter(Initials==Participant) %>% arrange(as.numeric(Clinical_Visit_Number))
  temp_daily_mfq <- daily_mfqs %>% filter(Initials==Participant)

  cat("  \n",  "  \n###",  iter, "->", as.character(temp_demo[1,1]), as.character(temp_demo[1,2]), "(", as.character(temp_demo[1,3]), ")", "-> SDAN:", 
      as.character(temp_demo[1,4]), "-> Age:", as.character(temp_demo[1,5]), "-> Sex:", as.character(temp_demo[1,6]), "-> Diagnosis:", as.character(temp_demo[1,7]), 
      "-> IRTA:", as.character(temp_demo[1,8]))

  cat("  \nAdmission & most recent medications:")
  med_data <- flextable(temp_meds, col_keys = c("Clinical_Visit_Number", "Clinical_Visit_Date2", "Medication_list")) %>%
    set_header_labels(., Clinical_Visit_Number="Week",  Clinical_Visit_Date2="Date", Medication_list="Medication") %>%
    fontsize(., size=8, part="all") %>% align(., align = "left", part="all") %>% FitFlextableToPage(.)
  cat(knit_print(med_data))

  cat("  \nInpatient scores:")
  questionnaire_data <- flextable(temp_psych, col_keys = c("Clinical_Visit_Number", "Clinical_Visit_Date2", "s_mfq1w_tot", 
      "s_ari1w_tot", "s_scared_tot", "s_shaps_tot", "s_lsas_tot", "s_vadis_tot", "s_rumination_tot", "s_chocir_symptom_tot", 
      "s_chocir_impairment_tot", "s_seq_tot", "p_conners_tot", "c_snap_tot", "c_cybocs_ob_tot",
      "c_cybocs_com_tot", "c_ygtss_severity_tot", "c_ygtss_tot")) %>% 
    set_header_labels(., Clinical_Visit_Number="Week",  Clinical_Visit_Date2="Date", s_mfq1w_tot="MFQ", s_ari1w_tot="ARI",
       s_scared_tot="SCARED", s_shaps_tot="SHAPS", s_lsas_tot="LSAS", s_vadis_tot="VADIS", s_rumination_tot="RUM", s_chocir_symptom_tot="CHOCIR:S",
       s_chocir_impairment_tot="CHOCIR:I", s_seq_tot="SEQ", p_conners_tot="CONNERS", c_snap_tot="SNAP", c_cybocs_ob_tot="CYBOCS:O",
       c_cybocs_com_tot="CYBOCS:C", c_ygtss_severity_tot="YGTSS:S", c_ygtss_tot="YGTSS:T") %>% 
    colformat_num(col_keys = c("Clinical_Visit_Number", "Clinical_Visit_Date2", "s_mfq1w_tot", "s_ari1w_tot", "s_scared_tot",
      "s_shaps_tot", "s_lsas_tot", "s_vadis_tot", "s_rumination_tot", "s_chocir_symptom_tot", "s_chocir_impairment_tot", "s_seq_tot", "p_conners_tot", "c_snap_tot",
      "c_cybocs_ob_tot", "c_cybocs_com_tot", "c_ygtss_severity_tot", "c_ygtss_tot"), digits = 0, na_str = "") %>% 
    fontsize(., size=8, part="all") %>% align(., align = "left", part="all") %>%
    FitFlextableToPage2(.)
  cat(knit_print(questionnaire_data))
  
  # cat("  \nDaily MFQs:  \n")
  # daily_mfq_data <- flextable(temp_daily_mfq, col_keys = c("s_mfq1d_date3", "s_mfq1d_tot")) %>%
  #   set_header_labels(., s_mfq1d_date3="Date", s_mfq1d_tot="Daily MFQ total") %>%
  #   fontsize(., size=8, part="all") %>% align(., align = "left", part="all") %>% FitFlextableToPage2(.)
  # cat(knit_print(daily_mfq_data))
  
  cat("  \n")
  daily_mfq_graph <- temp_daily_mfq %>% 
    ggplot(aes(x = s_mfq1d_date, y = s_mfq1d_tot)) + geom_point(size=3) + geom_line(size=0.25) +
    scale_x_date(date_break = "1 week", date_labels = "%d/%m") + geom_text(aes(label=s_mfq1d_tot), hjust=0, vjust=-1) +
    ylim(0,27) + theme_classic() + ggtitle("Daily MFQ\n") + ylab("MFQ total\n") + xlab("\nDate\n")
  knit_print(daily_mfq_graph)
  
  cat("  \n",  "  \n***")

}
  
```

##### Description of measures: 

```{r echo=FALSE, warning=FALSE, message=FALSE, results="asis"}

measures <- tibble(Abbreviation=c("MFQ", "ARI", "SCARED", "SHAPS", "LSAS", "VADIS", "RUM", "CHOCIR:S", "CHOCIR:I", "SEQ", "CONNERS", 
                                  "SNAP", "CYBOCS:O", "CYBOCS:C", "YGTSS:S", "YGTSS:T"),
                   Measure=c("Mood and Feelings Questionnaire", "Affective Reactivity Index", "Self-Report for Childhood Anxiety Related Emotional Disorders", 
                             "Snaith-Hamilton Pleasure Scale", "Liebowitz Social Anxiety Scale", "Child Depression Rating Scale", "Rumination Scale", 
                             "Obsession Compulsive Inventory Revised (symptom total)", "Obsession Compulsive Inventory Revised (impairment total)", 
                             "Self-efficacy Questionnaire", "Conners Comprehensive Behavior Rating Scale", "Swanson, Nolan and Pelham-IV Questionnaire", 
                             "Children's Yale-Brown Obsessive Compulsive Scale (obsessions subscale)", 
                             "Children's Yale-Brown Obsessive Compulsive Scale (compulsions subscale)", 
                             "Yale Global Tic Severity Scale (severity subscale)", 
                             "Yale Global Tic Severity Scale (total = severity + impairment)"))
measure_table <- flextable(measures) %>% fontsize(., size=8, part="all") %>% align(., align = "left", part="all") %>% FitFlextableToPage2(.)
cat(knit_print(measure_table))

``` 

```{r echo=FALSE, warning=FALSE, message=FALSE, results="hide" }

# removing finished variables

rm(temp_demo, temp_meds, temp_psych, temp_daily_mfq, questionnaire_data, med_data, FitFlextableToPage2)
rm(med_repeats, med_temp, Participant, i, j, iter, iter2, medication_data, current_inpatients, psychometric_data, inpatient_list)
# daily_mfq_data

```
